/**
 * Session metrics collector. See `NOTES.md` for the full design and the
 * non-obvious decisions.
 *
 * Two sharply separated parts, and the separation is what makes this file
 * testable without touching the filesystem or git:
 *
 * - **Pure derivation** (`deriveSessionRecord`, `deriveSubagentRecord`):
 *   takes already-parsed transcript rows (`unknown[]`) and a minimal
 *   context, returns a `SessionRecord`. No I/O. This is the part covered
 *   by the blocking golden test (`collect.spec.ts`).
 * - **I/O and orchestration** (from the «CLI» section down): reads the
 *   hook's stdin, the real transcript, writes the local spool, decides
 *   when to push, invoked by `.claude/hooks/metrics-collect.sh` on
 *   `SessionStart`/`Stop`/`SessionEnd`. Verified manually, not by this
 *   test file.
 *
 * This file doesn't import anything from the rest of whatever repository
 * hosts it: it only reads JSONL transcripts and git. No domain logic of
 * the adopting application must ever end up in here.
 */
import { execFileSync } from 'node:child_process';
import {
  appendFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Schema — schema_version: 1
// ---------------------------------------------------------------------------

export const SCHEMA_VERSION = 1 as const;

export type Isolation = 'primary' | 'worktree' | 'remote-web' | 'unknown';
export type ExitReason = 'turn_stop' | 'session_end' | 'orphan_recovered' | 'unknown';
export type CollectedBy = 'stop' | 'session_end' | 'session_start_sweep';

export interface TokenTotals {
  input: number;
  output: number;
  cache_creation: number;
  cache_read: number;
}

export interface SessionRecord {
  schema_version: 1;

  // Identity
  session_id: string;
  parent_session_id: string | null;
  agent_type: string | null;
  entrypoint: string | null;
  isolation: Isolation;

  // Time
  started_at: string;
  updated_at: string;
  ended_at: string | null;
  exit_reason: ExitReason;
  session_end_reason: string | null;

  // Git
  branch_start: string | null;
  branch_end: string | null;
  branches_seen: string[];
  cwd: string | null;

  // Cost
  model_primary: string | null;
  models_seen: string[];
  tokens: TokenTotals;
  tokens_by_model: Record<string, TokenTotals>;
  effort_levels_seen: string[];

  // Activity
  turns: number;
  assistant_messages: number;
  tool_calls: Record<string, number>;
  tool_calls_interrupted: number;
  files_read: string[];
  files_written: string[];
  transcript_entry_count: number;

  // Provenance of the record itself
  version: string | null;
  collected_by: CollectedBy;
  pushed_at: string | null;
}

/** Names of tools that read a file: feed `files_read`. */
const READ_TOOLS = new Set(['Read', 'Grep', 'Glob']);
/** Names of tools that write a file: feed `files_written`. */
const WRITE_TOOLS = new Set(['Edit', 'Write', 'MultiEdit']);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function asString(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

function asNumber(value: unknown): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0;
}

/**
 * `effort` on the transcript is a string (`"high"`, observed live).
 * The hook's payload instead carries it as `{ level: "high" }` — different
 * source, same information. Both handled here so the field doesn't come
 * back `null` just because of the wrong shape.
 */
function asEffortLevel(value: unknown): string | null {
  const direct = asString(value);
  if (direct) return direct;
  if (isRecord(value)) return asString(value.level);
  return null;
}

/**
 * A user event counts as a turn only if its `message.content` contains at
 * least one block that is **not** `tool_result` (text, image, or any other
 * block that isn't a tool echo). A `type:"user"` event whose `content` is
 * **only** `tool_result` is generated by the client, not by a human
 * prompt, and must be excluded.
 */
function isRealUserTurn(row: Record<string, unknown>): boolean {
  const message = row.message;
  if (!isRecord(message)) return false;
  const content = message.content;
  if (typeof content === 'string') return content.length > 0;
  if (!Array.isArray(content)) return false;
  return content.some((block) => isRecord(block) && block.type !== 'tool_result');
}

/** Extracts `tool_use` blocks from the content of an assistant row. */
function toolUseBlocks(row: Record<string, unknown>): Record<string, unknown>[] {
  const message = row.message;
  if (!isRecord(message)) return [];
  const content = message.content;
  if (!Array.isArray(content)) return [];
  return content.filter(
    (block): block is Record<string, unknown> => isRecord(block) && block.type === 'tool_use',
  );
}

function emptyTokenTotals(): TokenTotals {
  return { input: 0, output: 0, cache_creation: 0, cache_read: 0 };
}

function addTokenTotals(target: TokenTotals, usage: Record<string, unknown>): void {
  target.input += asNumber(usage.input_tokens);
  target.output += asNumber(usage.output_tokens);
  target.cache_creation += asNumber(usage.cache_creation_input_tokens);
  target.cache_read += asNumber(usage.cache_read_input_tokens);
}

function pushDeduped(list: string[], seen: Set<string>, value: string | null): void {
  if (!value || seen.has(value)) return;
  seen.add(value);
  list.push(value);
}

export interface DeriveContext {
  sessionId: string;
  parentSessionId: string | null;
  /** `null` if the transcript doesn't carry a resolvable `agent_type` (local main sessions). */
  agentType: string | null;
  collectedBy: CollectedBy;
  endedAt: string | null;
  exitReason: ExitReason;
  sessionEndReason: string | null;
  /** `pushed_at` of the previous record, if this derivation isn't followed by a push. */
  pushedAt: string | null;
  /** `true` if the hook saw `CLAUDE_CODE_REMOTE=true` in its own environment. */
  sawRemoteEnv: boolean;
  /** `CLAUDE_PROJECT_DIR` at collection time: distinguishes `cwd === repo` from a worktree. */
  repoRootHint: string | null;
  /** Fallback timestamp when the transcript carries no dated event (injected to stay pure/testable). */
  nowIso: string;
}

/**
 * Pure derivation: no I/O. Takes the already-parsed rows of **one** JSONL
 * file (main transcript or a sub-agent transcript — same shape) and
 * produces the `SessionRecord`.
 */
export function deriveSessionRecord(rows: unknown[], context: DeriveContext): SessionRecord {
  const branchesSeen: string[] = [];
  const branchesSeenSet = new Set<string>();
  const modelsSeen: string[] = [];
  const modelsSeenSet = new Set<string>();
  const effortLevelsSeen: string[] = [];
  const effortLevelsSeenSet = new Set<string>();
  const filesRead: string[] = [];
  const filesReadSet = new Set<string>();
  const filesWritten: string[] = [];
  const filesWrittenSet = new Set<string>();

  let branchStart: string | null = null;
  let branchEnd: string | null = null;
  let cwd: string | null = null;
  let entrypoint: string | null = null;
  let version: string | null = null;
  let startedAt: string | null = null;
  let updatedAt: string | null = null;

  let turns = 0;
  let toolCallsInterrupted = 0;
  const toolCalls: Record<string, number> = {};

  const tokens = emptyTokenTotals();
  const tokensByModel: Record<string, TokenTotals> = {};

  // A `requestId` can repeat across multiple non-consecutive rows (a
  // tool_result in between doesn't close the streaming turn, verified
  // live): counting `assistant_messages` and summing tokens must be done
  // **only once per requestId**, not per row — summing per row would
  // multiply the cost by however many rows share the same `requestId`
  // (observed: up to 5 identical `usage` rows for a single real turn).
  const seenRequestIds = new Set<string>();
  let assistantMessages = 0;

  for (let index = 0; index < rows.length; index++) {
    const row = rows[index];
    if (!isRecord(row)) continue;

    const rowType = asString(row.type);

    const rowCwd = asString(row.cwd);
    if (rowCwd) cwd = rowCwd;
    const rowEntrypoint = asString(row.entrypoint);
    if (rowEntrypoint && !entrypoint) entrypoint = rowEntrypoint;
    const rowVersion = asString(row.version);
    if (rowVersion) version = rowVersion;

    const rowBranch = asString(row.gitBranch);
    if (rowBranch) {
      if (!branchStart) branchStart = rowBranch;
      branchEnd = rowBranch;
      pushDeduped(branchesSeen, branchesSeenSet, rowBranch);
    }

    const rowTimestamp = asString(row.timestamp);
    if (rowTimestamp) {
      if (!startedAt) startedAt = rowTimestamp;
      updatedAt = rowTimestamp;
    }

    const rowEffort = asEffortLevel(row.effort);
    if (rowEffort) pushDeduped(effortLevelsSeen, effortLevelsSeenSet, rowEffort);

    if (rowType === 'user' && isRealUserTurn(row)) {
      turns += 1;
    }
    if (rowType === 'user') {
      const toolUseResult = row.toolUseResult;
      if (isRecord(toolUseResult) && toolUseResult.interrupted === true) {
        toolCallsInterrupted += 1;
      }
    }

    if (rowType === 'assistant') {
      const requestId = asString(row.requestId) ?? `__row_${index}`;
      if (!seenRequestIds.has(requestId)) {
        seenRequestIds.add(requestId);
        assistantMessages += 1;

        const message = row.message;
        const model = isRecord(message) ? asString(message.model) : null;
        const usage = isRecord(message) && isRecord(message.usage) ? message.usage : null;
        if (model) {
          pushDeduped(modelsSeen, modelsSeenSet, model);
          if (usage) {
            addTokenTotals(tokens, usage);
            tokensByModel[model] ??= emptyTokenTotals();
            addTokenTotals(tokensByModel[model], usage);
          }
        }
      }

      // `tool_use` blocks, unlike `usage`, do **not** repeat across rows
      // with the same `requestId`: each row can carry a different call
      // (observed: 4 distinct `Read`s under a single `requestId`, each its
      // own row). They must therefore be counted on **every** row.
      for (const block of toolUseBlocks(row)) {
        const name = asString(block.name);
        if (!name) continue;
        toolCalls[name] = (toolCalls[name] ?? 0) + 1;

        const input = block.input;
        const filePath = isRecord(input) ? asString(input.file_path) : null;
        if (filePath && READ_TOOLS.has(name)) pushDeduped(filesRead, filesReadSet, filePath);
        if (filePath && WRITE_TOOLS.has(name)) pushDeduped(filesWritten, filesWrittenSet, filePath);
      }
    }
  }

  let modelPrimary: string | null = null;
  let maxOutput = -1;
  for (const model of modelsSeen) {
    const output = tokensByModel[model]?.output ?? 0;
    if (output > maxOutput) {
      maxOutput = output;
      modelPrimary = model;
    }
  }

  let isolation: Isolation = 'unknown';
  if (context.sawRemoteEnv) {
    isolation = 'remote-web';
  } else if (cwd?.includes('/.claude/worktrees/')) {
    isolation = 'worktree';
  } else if (cwd && context.repoRootHint && cwd === context.repoRootHint) {
    isolation = 'primary';
  }

  return {
    schema_version: SCHEMA_VERSION,
    session_id: context.sessionId,
    parent_session_id: context.parentSessionId,
    agent_type: context.agentType,
    entrypoint,
    isolation,
    started_at: startedAt ?? context.nowIso,
    updated_at: updatedAt ?? startedAt ?? context.nowIso,
    ended_at: context.endedAt,
    exit_reason: context.exitReason,
    session_end_reason: context.sessionEndReason,
    branch_start: branchStart,
    branch_end: branchEnd,
    branches_seen: branchesSeen,
    cwd,
    model_primary: modelPrimary,
    models_seen: modelsSeen,
    tokens,
    tokens_by_model: tokensByModel,
    effort_levels_seen: effortLevelsSeen,
    turns,
    assistant_messages: assistantMessages,
    tool_calls: toolCalls,
    tool_calls_interrupted: toolCallsInterrupted,
    files_read: filesRead,
    files_written: filesWritten,
    transcript_entry_count: rows.length,
    version,
    collected_by: context.collectedBy,
    pushed_at: context.pushedAt,
  };
}

export interface SubagentMeta {
  agentType?: unknown;
  worktreeCleanlyRemoved?: unknown;
}

export interface DeriveSubagentContext {
  /** `agent-<id>`: the stem of the `agent-<id>.jsonl`/`agent-<id>.meta.json` files. */
  sessionId: string;
  /** The `session_id` of the parent session (the name of the folder containing `subagents/`). */
  parentSessionId: string;
  collectedBy: CollectedBy;
  pushedAt: string | null;
  sawRemoteEnv: boolean;
  repoRootHint: string | null;
  nowIso: string;
}

/**
 * Derives a sub-agent's record by composing the same main-transcript
 * parser with `agentType`/`parent_session_id`, which **don't** live in the
 * child's transcript but in the adjacent `meta.json` and in the parent
 * folder's name.
 */
export function deriveSubagentRecord(
  meta: unknown,
  rows: unknown[],
  context: DeriveSubagentContext,
): SessionRecord {
  const agentType = isRecord(meta) ? asString(meta.agentType) : null;
  return deriveSessionRecord(rows, {
    sessionId: context.sessionId,
    parentSessionId: context.parentSessionId,
    agentType,
    collectedBy: context.collectedBy,
    endedAt: null,
    exitReason: 'unknown',
    sessionEndReason: null,
    pushedAt: context.pushedAt,
    sawRemoteEnv: context.sawRemoteEnv,
    repoRootHint: context.repoRootHint,
    nowIso: context.nowIso,
  });
}

// ---------------------------------------------------------------------------
// I/O and orchestration — not covered by collect.spec.ts (verified manually).
// Isolated from the pure derivation above by construction: every function
// below touches the filesystem, git, or the process environment.
// ---------------------------------------------------------------------------

const PUSH_MIN_INTERVAL_MINUTES = 5;
/** `SessionStart` sweep window: not worth scanning months of history on every startup. */
const SWEEP_WINDOW_DAYS = 7;

function moduleDir(): string {
  return dirname(fileURLToPath(import.meta.url));
}

function repoRoot(): string {
  return process.env.CLAUDE_PROJECT_DIR ?? resolve(moduleDir(), '../..');
}

function spoolDir(): string {
  return join(repoRoot(), '.claude', 'metrics-spool');
}

function recordsDir(): string {
  return join(spoolDir(), 'records');
}

function hookLogPath(): string {
  return join(spoolDir(), 'hook.log');
}

function log(message: string): void {
  try {
    mkdirSync(spoolDir(), { recursive: true });
    appendFileSync(hookLogPath(), `${new Date().toISOString()} ${message}\n`);
  } catch {
    // The log is a safeguard, not the task: if even this fails, there's no
    // second place to report it without risking blocking the hook.
  }
}

function readJsonlRows(path: string): unknown[] {
  if (!existsSync(path)) return [];
  const text = readFileSync(path, 'utf8');
  const rows: unknown[] = [];
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      rows.push(JSON.parse(trimmed));
    } catch {
      log(`non-JSON row ignored in ${path}`);
    }
  }
  return rows;
}

function readJsonFile(path: string): unknown {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    log(`non-JSON file ignored: ${path}`);
    return null;
  }
}

function writeSpoolRecord(record: SessionRecord): string {
  mkdirSync(recordsDir(), { recursive: true });
  const path = join(recordsDir(), `${record.session_id}.json`);
  writeFileSync(path, `${JSON.stringify(record, null, 2)}\n`, 'utf8');
  return path;
}

function readSpoolRecord(sessionId: string): SessionRecord | null {
  const parsed = readJsonFile(join(recordsDir(), `${sessionId}.json`));
  return isRecord(parsed) ? (parsed as unknown as SessionRecord) : null;
}

/**
 * Push to `refs/agent-metrics/sessions/<session_id>`, via plumbing (never a
 * working-tree checkout in progress). `--force` is safe: that ref exists
 * only for this session.
 */
function pushRecord(record: SessionRecord): boolean {
  try {
    const cwd = repoRoot();
    const json = `${JSON.stringify(record, null, 2)}\n`;
    const blob = execFileSync('git', ['hash-object', '-w', '--stdin'], { cwd, input: json })
      .toString()
      .trim();
    const treeEntry = `100644 blob ${blob}\trecord.json\n`;
    const tree = execFileSync('git', ['mktree'], { cwd, input: treeEntry }).toString().trim();
    const commit = execFileSync(
      'git',
      ['commit-tree', tree, '-m', `metrics: ${record.session_id}`],
      { cwd },
    )
      .toString()
      .trim();
    execFileSync(
      'git',
      ['push', '--force', 'origin', `${commit}:refs/agent-metrics/sessions/${record.session_id}`],
      { cwd, stdio: 'ignore' },
    );
    return true;
  } catch (error) {
    log(`push failed for ${record.session_id}: ${(error as Error).message}`);
    return false;
  }
}

interface HookPayload {
  session_id?: string;
  transcript_path?: string;
  cwd?: string;
  agent_type?: string;
  hook_event_name?: string;
  /**
   * `Stop`/`SubagentStop`: present when the hook is already re-running
   * (`CLAUDE_CODE_STOP_HOOK_BLOCK_CAP` limit). Name and type confirmed live
   * with a disposable headless `claude -p` session in a scratch directory
   * outside the repo, with temporary `Stop`/`SessionEnd` hooks that wrote
   * the received stdin to a file (later removed, never committed). Real
   * payload: `"stop_hook_active":false` — boolean, as expected.
   */
  stop_hook_active?: boolean;
  /**
   * `SessionEnd`: reason declared by the runtime. Confirmed live with the
   * same probe: real payload `"reason":"other"` — string, as expected.
   */
  reason?: string;
}

function readStdin(): string {
  try {
    return readFileSync(0, 'utf8');
  } catch {
    return '';
  }
}

function parseHookPayload(): HookPayload {
  const raw = readStdin();
  if (!raw.trim()) return {};
  try {
    const parsed: unknown = JSON.parse(raw);
    return isRecord(parsed) ? (parsed as HookPayload) : {};
  } catch {
    log('non-JSON hook payload, ignored');
    return {};
  }
}

function subagentsDirFor(transcriptPath: string, sessionId: string): string {
  return join(dirname(transcriptPath), sessionId, 'subagents');
}

/**
 * Enumerates `subagents/*.meta.json` next to `sessionId`'s transcript and
 * writes/pushes a record for each — covers sub-agents without needing a
 * hook in their isolated environment: the parent finds them locally as
 * soon as they finish.
 */
function collectSubagents(
  transcriptPath: string,
  parentSessionId: string,
  collectedBy: CollectedBy,
  sawRemoteEnv: boolean,
  nowIso: string,
): void {
  const dir = subagentsDirFor(transcriptPath, parentSessionId);
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir)) {
    if (!entry.endsWith('.meta.json')) continue;
    const stem = entry.slice(0, -'.meta.json'.length); // "agent-<id>"
    const meta = readJsonFile(join(dir, `${stem}.meta.json`));
    const rows = readJsonlRows(join(dir, `${stem}.jsonl`));
    const previous = readSpoolRecord(stem);
    const record = deriveSubagentRecord(meta, rows, {
      sessionId: stem,
      parentSessionId,
      collectedBy,
      pushedAt: previous?.pushed_at ?? null,
      sawRemoteEnv,
      repoRootHint: repoRoot(),
      nowIso,
    });
    writeSpoolRecord(record);
    maybePush(record, previous, collectedBy);
  }
}

function minutesSince(iso: string, nowIso: string): number {
  const then = Date.parse(iso);
  const now = Date.parse(nowIso);
  if (Number.isNaN(then) || Number.isNaN(now)) return Number.POSITIVE_INFINITY;
  return (now - then) / 60_000;
}

/**
 * Pure decision, no I/O — testable without touching the filesystem or
 * git:
 *
 * - `stop` only pushes past the time threshold since the last successful
 *   push **of this session** (`previous.pushed_at`), to stay proportional
 *   to wall-clock time rather than the number of turns.
 * - `session_end` **always** pushes: it's the last chance.
 * - `session_start_sweep` pushes **only** records whose `updated_at` is
 *   more recent than that record's own last successful push
 *   (`record.pushed_at`, not `previous`: the sweep doesn't derive a new
 *   state, it re-proposes the one already on disk) or that were never
 *   pushed. Without this guard the sweep would unconditionally re-push
 *   every file in `recordsDir()` on every startup — traffic proportional
 *   to the total local history, not to the work of the session that's
 *   starting, defeating the derivation/push decoupling described above.
 */
export function isPushDue(
  record: Pick<SessionRecord, 'updated_at' | 'pushed_at'>,
  previous: Pick<SessionRecord, 'pushed_at'> | null,
  collectedBy: CollectedBy,
): boolean {
  if (collectedBy === 'session_end') return true;
  if (collectedBy === 'session_start_sweep') {
    if (!record.pushed_at) return true;
    return Date.parse(record.updated_at) > Date.parse(record.pushed_at);
  }
  return (
    !previous?.pushed_at || minutesSince(previous.pushed_at, record.updated_at) >= PUSH_MIN_INTERVAL_MINUTES
  );
}

function maybePush(
  record: SessionRecord,
  previous: SessionRecord | null,
  collectedBy: CollectedBy,
): void {
  if (!isPushDue(record, previous, collectedBy)) return;

  const pushed = pushRecord(record);
  if (pushed) {
    record.pushed_at = new Date().toISOString();
    writeSpoolRecord(record);
  }
}

function handleStopOrSessionEnd(event: 'stop' | 'session_end'): void {
  const payload = parseHookPayload();
  const sessionId = payload.session_id;
  const transcriptPath = payload.transcript_path;
  if (!sessionId || !transcriptPath) {
    log(`incomplete payload on ${event}: missing session_id/transcript_path`);
    return;
  }

  const nowIso = new Date().toISOString();
  const rows = readJsonlRows(transcriptPath);
  const previous = readSpoolRecord(sessionId);
  const collectedBy: CollectedBy = event === 'stop' ? 'stop' : 'session_end';

  const record = deriveSessionRecord(rows, {
    sessionId,
    parentSessionId: null,
    agentType: payload.agent_type ?? previous?.agent_type ?? null,
    collectedBy,
    endedAt: event === 'session_end' ? nowIso : null,
    exitReason: event === 'session_end' ? 'session_end' : 'turn_stop',
    sessionEndReason: event === 'session_end' ? (payload.reason ?? null) : null,
    pushedAt: previous?.pushed_at ?? null,
    sawRemoteEnv: process.env.CLAUDE_CODE_REMOTE === 'true',
    repoRootHint: repoRoot(),
    nowIso,
  });

  writeSpoolRecord(record);
  maybePush(record, previous, collectedBy);
  collectSubagents(
    transcriptPath,
    sessionId,
    collectedBy,
    process.env.CLAUDE_CODE_REMOTE === 'true',
    nowIso,
  );
}

function handleSessionStart(): void {
  const payload = parseHookPayload();
  const nowIso = new Date().toISOString();
  const sawRemoteEnv = process.env.CLAUDE_CODE_REMOTE === 'true';

  // 1. Sweep of local records not yet pushed (or whose `updated_at` is
  //    more recent than the last successful push).
  if (existsSync(recordsDir())) {
    for (const entry of readdirSync(recordsDir())) {
      if (!entry.endsWith('.json')) continue;
      const record = readSpoolRecord(entry.slice(0, -'.json'.length));
      if (!record) continue;
      maybePush(record, record, 'session_start_sweep');
    }
  }

  // 2. Orphan sessions: recent transcripts with no local record —
  //    "died before any Stop ever fired".
  const cwd = payload.cwd ?? process.cwd();
  const transcriptPath = payload.transcript_path;
  if (!transcriptPath) return;
  const projectDir = dirname(transcriptPath);
  if (!existsSync(projectDir)) return;

  const cutoffMs = Date.now() - SWEEP_WINDOW_DAYS * 24 * 60 * 60 * 1000;
  for (const entry of readdirSync(projectDir)) {
    if (!entry.endsWith('.jsonl')) continue;
    const sessionId = entry.slice(0, -'.jsonl'.length);
    const fullPath = join(projectDir, entry);
    if (statSync(fullPath).mtimeMs < cutoffMs) continue;
    if (readSpoolRecord(sessionId)) continue; // already covered by a previous Stop

    const rows = readJsonlRows(fullPath);
    const record = deriveSessionRecord(rows, {
      sessionId,
      parentSessionId: null,
      agentType: null,
      collectedBy: 'session_start_sweep',
      endedAt: null,
      exitReason: 'orphan_recovered',
      sessionEndReason: null,
      pushedAt: null,
      sawRemoteEnv,
      repoRootHint: repoRoot(),
      nowIso,
    });
    writeSpoolRecord(record);
    maybePush(record, null, 'session_start_sweep');
    collectSubagents(fullPath, sessionId, 'session_start_sweep', sawRemoteEnv, nowIso);
  }

  void cwd; // reserved: not needed today beyond reading the payload above.
}

function main(): void {
  const event = process.argv[2];
  try {
    if (event === 'Stop') handleStopOrSessionEnd('stop');
    else if (event === 'SessionEnd') handleStopOrSessionEnd('session_end');
    else if (event === 'SessionStart') handleSessionStart();
    else log(`unknown event: ${String(event)}`);
  } catch (error) {
    // Never an error perceived by the agent: the safeguard is the log, not
    // the exit code.
    log(`unhandled error: ${(error as Error).stack ?? String(error)}`);
  }
}

// Only run from the CLI (`tsx collect.ts <event>`), not when imported by
// the test: `import.meta.url` matches the entrypoint only in the former case.
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
