/**
 * Blocking golden test: no change to `collect.ts` is ready for final
 * review without these two staying green. Covers the three points where
 * the derivation can silently get it wrong: the filter on `tool_result`
 * echoes, grouping by `requestId`, and the derivation of
 * `agent_type`/`parent_session_id` from `subagents/*.meta.json`.
 *
 * The two fixtures (`fixtures/session.jsonl`, `fixtures/subagent.{meta,jsonl}`)
 * are real transcripts from a development session, truncated with every
 * prompt/tool content replaced by a placeholder, and with paths/branch
 * names made generic — real structure, content and identifiers removed.
 * `fixtures/*.expected.json` was generated by the same function below and
 * verified by hand against the fixtures, row by row.
 *
 * The "turns red if it breaks" checks mentioned in the comments were done
 * by hand while writing this file (fixture or expected value altered,
 * `vitest run` re-run, then restored) — they are not re-run on every run.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  deriveSessionRecord,
  deriveSubagentRecord,
  isPushDue,
  type SessionRecord,
} from './collect.js';

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), 'fixtures');

function readJsonl(path: string): unknown[] {
  return readFileSync(path, 'utf8')
    .split('\n')
    .filter((line) => line.trim().length > 0)
    .map((line) => JSON.parse(line) as unknown);
}

function readJson(path: string): unknown {
  return JSON.parse(readFileSync(path, 'utf8'));
}

describe('deriveSessionRecord — fixture A, main transcript', () => {
  const rows = readJsonl(join(fixturesDir, 'session.jsonl'));
  const expected = readJson(join(fixturesDir, 'session.expected.json')) as SessionRecord;

  const record = deriveSessionRecord(rows, {
    sessionId: '06148b2e-08ba-4490-952e-c4ca62d174bf',
    parentSessionId: null,
    agentType: 'tech-lead',
    collectedBy: 'stop',
    endedAt: null,
    exitReason: 'turn_stop',
    sessionEndReason: null,
    pushedAt: null,
    sawRemoteEnv: false,
    repoRootHint: '/Users/dev/workspaces/example-project/example-project',
    nowIso: '2026-08-25T09:00:00.000Z',
  });

  it('matches the expected record, field by field', () => {
    expect(record).toStrictEqual(expected);
  });

  it('excludes tool_result echoes from the turn count (fixture: 1 real turn out of 7 user rows)', () => {
    // The fixture carries 1 single `user` event with real text (index 3)
    // and 7 `tool_result` echoes (indices 10, 12, 18, 20, 22, 28, 30, 32,
    // 34 — a subset). If the filter disappeared, `turns` would silently
    // climb to 8+: here it's pinned at 1.
    expect(record.turns).toBe(1);
  });

  it('groups assistant rows by requestId even when a tool_result separates them (fixture: 3 distinct requestIds over 15 assistant rows)', () => {
    // Three requestIds, the first of which (rows 8, 9, 11) is interrupted
    // by a tool_result echo (row 10) and still continues with the same
    // requestId — the non-consecutive case verified live. If the grouping
    // went back to counting per row, the number would be 15.
    expect(record.assistant_messages).toBe(3);
  });

  it('sums tokens only once per requestId, not per row', () => {
    // `usage` is identical across every row that shares a requestId
    // (observed live): summing it per row would triple the cost of rows
    // 8/9/11. The expected total is that of 3 real responses, not 15.
    expect(record.tokens.output).toBe(expected.tokens.output);
    expect(record.tokens.output).toBeLessThan(2000);
  });
});

describe('deriveSubagentRecord — fixture B, a sub-agent\'s meta.json/jsonl pair', () => {
  const rows = readJsonl(join(fixturesDir, 'subagent.jsonl'));
  const meta = readJson(join(fixturesDir, 'subagent.meta.json'));
  const expected = readJson(join(fixturesDir, 'subagent.expected.json')) as SessionRecord;

  const record = deriveSubagentRecord(meta, rows, {
    sessionId: 'agent-ae4fd0ecea21bfc0f',
    parentSessionId: '06148b2e-08ba-4490-952e-c4ca62d174bf',
    collectedBy: 'stop',
    pushedAt: null,
    sawRemoteEnv: false,
    repoRootHint: '/Users/dev/workspaces/example-project/example-project',
    nowIso: '2026-08-25T09:00:00.000Z',
  });

  it('matches the expected record, field by field', () => {
    expect(record).toStrictEqual(expected);
  });

  it('agent_type matches meta.json\'s agentType exactly (not null, not a different value)', () => {
    expect(meta).toMatchObject({ agentType: 'implementer' });
    expect(record.agent_type).toBe('implementer');
    expect(record.agent_type).not.toBeNull();
  });

  it('parent_session_id is populated from the context (doesn\'t live in meta.json nor in the child\'s transcript)', () => {
    expect(meta).not.toHaveProperty('parentSessionId');
    expect(record.parent_session_id).toBe('06148b2e-08ba-4490-952e-c4ca62d174bf');
  });

  it('classifies isolation: "worktree" from a cwd under .claude/worktrees/, as in the real fixture', () => {
    expect(record.isolation).toBe('worktree');
  });
});

// ---------------------------------------------------------------------------
// Additional synthetic cases — not real fixtures, hand-built arrays to
// exercise branches the two real fixtures above don't cover. They don't
// replace the fixtures (blocking); they complement them.
// ---------------------------------------------------------------------------

describe('deriveSessionRecord — additional synthetic cases', () => {
  const baseContext = {
    sessionId: 'synthetic-session',
    parentSessionId: null,
    agentType: null,
    collectedBy: 'stop' as const,
    endedAt: null,
    exitReason: 'turn_stop' as const,
    sessionEndReason: null,
    pushedAt: null,
    sawRemoteEnv: false,
    repoRootHint: '/repo',
    nowIso: '2026-08-25T09:00:00.000Z',
  };

  function assistantRow(opts: {
    requestId: string;
    model: string;
    output: number;
    gitBranch: string;
    content: unknown[];
  }) {
    return {
      type: 'assistant',
      requestId: opts.requestId,
      timestamp: '2026-08-25T09:00:00.000Z',
      gitBranch: opts.gitBranch,
      cwd: '/repo',
      entrypoint: 'claude-vscode',
      version: '2.1.229',
      effort: 'high',
      message: {
        model: opts.model,
        content: opts.content,
        usage: {
          input_tokens: 1,
          output_tokens: opts.output,
          cache_creation_input_tokens: 0,
          cache_read_input_tokens: 0,
        },
      },
    };
  }

  it('deduplicates branches_seen while keeping first-seen order, distinguishing branch_start from branch_end', () => {
    const rows = [
      assistantRow({ requestId: 'r1', model: 'claude-sonnet-5', output: 10, gitBranch: 'main', content: [] }),
      assistantRow({ requestId: 'r2', model: 'claude-sonnet-5', output: 10, gitBranch: 'feat/x', content: [] }),
      assistantRow({ requestId: 'r3', model: 'claude-sonnet-5', output: 10, gitBranch: 'main', content: [] }),
    ];
    const record = deriveSessionRecord(rows, baseContext);
    expect(record.branch_start).toBe('main');
    expect(record.branch_end).toBe('main');
    expect(record.branches_seen).toEqual(['main', 'feat/x']);
  });

  it('picks model_primary as the model with the most output_tokens, not the first one seen', () => {
    const rows = [
      assistantRow({ requestId: 'r1', model: 'claude-haiku-5', output: 5, gitBranch: 'main', content: [] }),
      assistantRow({ requestId: 'r2', model: 'claude-sonnet-5', output: 500, gitBranch: 'main', content: [] }),
    ];
    const record = deriveSessionRecord(rows, baseContext);
    expect(record.models_seen).toEqual(['claude-haiku-5', 'claude-sonnet-5']);
    expect(record.model_primary).toBe('claude-sonnet-5');
  });

  it('counts tool_calls_interrupted from toolUseResult.interrupted === true on a tool_result echo', () => {
    const rows = [
      {
        type: 'user',
        timestamp: '2026-08-25T09:00:00.000Z',
        gitBranch: 'main',
        cwd: '/repo',
        message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: 'x' }] },
        toolUseResult: { interrupted: true, stdout: '', stderr: '', isImage: false, noOutputExpected: false },
      },
      {
        type: 'user',
        timestamp: '2026-08-25T09:00:01.000Z',
        gitBranch: 'main',
        cwd: '/repo',
        message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't2', content: 'x' }] },
        toolUseResult: { interrupted: false, stdout: '', stderr: '', isImage: false, noOutputExpected: false },
      },
    ];
    const record = deriveSessionRecord(rows, baseContext);
    expect(record.tool_calls_interrupted).toBe(1);
    expect(record.turns).toBe(0); // both remain echoes, no real turn
  });

  it('populates files_written from Edit/Write/MultiEdit, distinct from files_read', () => {
    const rows = [
      assistantRow({
        requestId: 'r1',
        model: 'claude-sonnet-5',
        output: 10,
        gitBranch: 'main',
        content: [
          { type: 'tool_use', name: 'Read', input: { file_path: 'a.ts' } },
          { type: 'tool_use', name: 'Write', input: { file_path: 'b.ts' } },
          { type: 'tool_use', name: 'Edit', input: { file_path: 'b.ts' } },
        ],
      }),
    ];
    const record = deriveSessionRecord(rows, baseContext);
    expect(record.files_read).toEqual(['a.ts']);
    expect(record.files_written).toEqual(['b.ts']);
    expect(record.tool_calls).toEqual({ Read: 1, Write: 1, Edit: 1 });
  });

  it('a transcript with no dated event falls back to nowIso instead of throwing', () => {
    const record = deriveSessionRecord([{ type: 'agent-setting', agentSetting: 'tech-lead' }], baseContext);
    expect(record.started_at).toBe(baseContext.nowIso);
    expect(record.updated_at).toBe(baseContext.nowIso);
    expect(record.turns).toBe(0);
  });
});

describe('isPushDue — when each event actually pushes', () => {
  it('SessionStart\'s sweep does NOT re-push a record already pushed and unchanged since then', () => {
    // `updated_at` no more recent than `pushed_at`: no new write to
    // consolidate since the last successful push. If the sweep pushed
    // anyway, remote traffic would grow with the entire local history on
    // every startup instead of with the current session's work.
    const due = isPushDue(
      { updated_at: '2026-08-25T09:00:00.000Z', pushed_at: '2026-08-25T09:05:00.000Z' },
      null,
      'session_start_sweep',
    );
    expect(due).toBe(false);
  });

  it('SessionStart\'s sweep pushes a record more recent than its pushed_at, or never pushed', () => {
    const staleSincePush = isPushDue(
      { updated_at: '2026-08-25T09:10:00.000Z', pushed_at: '2026-08-25T09:05:00.000Z' },
      null,
      'session_start_sweep',
    );
    expect(staleSincePush).toBe(true);

    const neverPushed = isPushDue(
      { updated_at: '2026-08-25T09:10:00.000Z', pushed_at: null },
      null,
      'session_start_sweep',
    );
    expect(neverPushed).toBe(true);
  });

  it('SessionEnd always pushes, even a record identical to a just-succeeded push', () => {
    const due = isPushDue(
      { updated_at: '2026-08-25T09:00:00.000Z', pushed_at: '2026-08-25T09:00:00.000Z' },
      null,
      'session_end',
    );
    expect(due).toBe(true);
  });

  it('Stop respects the 5-minute threshold since the last successful push OF THIS session', () => {
    const tooSoon = isPushDue(
      { updated_at: '2026-08-25T09:04:00.000Z', pushed_at: null },
      { pushed_at: '2026-08-25T09:00:00.000Z' },
      'stop',
    );
    expect(tooSoon).toBe(false);

    const dueByThreshold = isPushDue(
      { updated_at: '2026-08-25T09:05:00.000Z', pushed_at: null },
      { pushed_at: '2026-08-25T09:00:00.000Z' },
      'stop',
    );
    expect(dueByThreshold).toBe(true);
  });
});
